#!/bin/bash -e
## Run Puppet locally using puppet apply
output=$(/opt/puppetlabs/bin/puppet apply /etc/puppet/manifests/site.pp --modulepath=modules/)

## Log status of the Puppet run
if [ $? -eq 0 ]
then
    /usr/bin/logger -i -t "puppet-run" "Puppet has run successfully"
    echo "$output" | /usr/bin/logger -i -t "puppet-run"
    exit 0
else
    /usr/bin/logger -i -t "puppet-run" "Puppet has ran into an error, please run Puppet manually"
    echo "$output" | /usr/bin/logger -i -t "puppet-run"
    exit 1
fi
